package com.swap.common.error;

public enum ErrorEnum {

	// GENERAL ERROR
	GEN_SYSTEM_ERROR(500), 
	// CATEGORY RELATED ERRORS
	CATEGORY_NOT_FOUND(400), INVALID_CATEGORY(400), CATEGORY_SERVICE_ERROR(500), 
	CATEGORY_DAO_ERROR(500), INVALID_CATEGORY_REQUEST(400), INVALID_CATEGORY_ID(400),
	INVALID_CATEGORY_NAME(400),
	
	GET_CATEGORY_FAILURE(500), GET_CATEGORIES_FAILURE(500), CREATE_CATEGORY_FAILURE(500),
	UPDATE_CATEGORY_FAILURE(500), DELETE_CATEGORY_FAILURE(500),
	//USER PROFILE RELATED ERRORS
	INVALID_USER_NAME(400),INVALID_USER_REQUEST(400),USER_NAME_CANNOT_BE_EMPTY(400), USER_CANNOT_BE_EMPTY(400),
	USER_NOT_FOUND(404),INVALID_EMAIL_ID(400),FIRST_NAME_CANNOT_BE_EMPTY(400),LAST_NAME_CANNOT_BE_EMPTY(400),
	// LISTING RELATED ERRORS
	INVALID_LISTING_REQUEST(400),INVALID_ITEM_ID(400),LISTING_DAO_ERROR(500),NOT_NULL_FIELDS_ERROR(400),INVALID_USER_ID(400),
	GET_LISTING_FAILURE(500),
	
	//IMAGE RELATED ERRORS
	GET_IMAGE_FAILURE(500),
	
	// SEARCH RELATED ERRORS
	INVALID_SEARCH_QUERY(400), SEARCH_SERVICE_FAILURE(500),
	
	// INTEREST RELATED ERRORS
	INVALID_INTEREST_REQUEST(400), INVALID_INTERESTED_USER_ID(400), INVALID_INTEREST_ID(400),
	INVALID_ORIGINAL_ITEM_USER_ID(400), INVALID_ONE_SIDED_INTEREST_FLAG(400), INVALID_SWAPPABLE_ITEMS_LIST(400),
	TOO_MANY_SWAPPABLE_ITEMS(400),NO_ITEMS_FOUND_FOR_USER(400),
	ITEM_DOES_NOT_BELONG_TO_USER(400),
	CREATE_INTEREST_FAILURE(500), DELETE_INTEREST_FAILURE(500),
	
	// REVIEW RELATED ERRORS
	INVALID_REVIEW_REQUEST(400), REVIEW_SERVICE_FAILURE(500),
	
	//LOGIN RELATED ERRORS
	ACCESS_TOKEN_EMPTY(403), PROVIDER_ID_EMPTY(400), INVALID_ACCESS_TOKEN(401);
	
	
	private int statusCode;

    private ErrorEnum(int statusCode) {
        this.statusCode = statusCode;
    }
    
    public int getStatusCode() {
    	return this.statusCode;
    }
}
